---
name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.new-release-version }}
      published: ${{ steps.version.outputs.new-release-published }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: npm
          cache-dependency-path: ".releaserc.yaml"
          node-version: lts/*
      - name: Semantic Release
        id: release
        run: |
          # Semantic Release
          npm install --no-save --no-package-lock \
            "@semantic-release/commit-analyzer" \
            "@semantic-release/release-notes-generator" \
            "@semantic-release/changelog" \
            "@semantic-release/git" \
            "@semantic-release/github" \
            "semantic-release-major-tag" \
            "conventional-changelog-conventionalcommits"
      - id: version
        uses: open-turo/actions-release/semantic-release@4d8a6b6aa2d051e7dba0429d8d08beef827b5ccd # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          ci: false

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.outputs.published == 'true'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v5
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6.1.0
        with:
          version: "0.7.12"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - run: |
          # Install dependencies
          uv sync --locked --all-extras --dev
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          cache: npm
          cache-dependency-path: ".releaserc.yaml"
          node-version: lts/*
      - name: Semantic Release
        id: release
        run: |
          # Semantic Release
          npm install --no-save --no-package-lock \
            "@semantic-release/commit-analyzer" \
            "@semantic-release/release-notes-generator" \
            "@semantic-release/changelog" \
            "@semantic-release/git" \
            "@semantic-release/github" \
            "semantic-release-major-tag" \
            "conventional-changelog-conventionalcommits"
      - id: version
        uses: open-turo/actions-release/semantic-release@94161cffd7a38c20a6e685406996b1cdb259f0d5 # v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          ci: false
      - run: |
          # Update version
          uv version ${{ steps.version.outputs.new-release-version }}
      - uses: actions-js/push@master
        with:
          message: "chore: ${{ steps.version.outputs.new-release-version }} [skip actions]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # We aren't actually publishing this to PyPI
      # - run: |
      #     # Build package
      #     uv build
      # - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
      - uses: open-turo/actions-release/semantic-release@4d8a6b6aa2d051e7dba0429d8d08beef827b5ccd # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
